# Site settings

source: .
destination: ./docs
title: "PCjs Machines"
email: Jeff@pcjs.org
description: >
  Welcome to PCjs, home of the original IBM PC in a web browser.
  The PCjs Project offers a variety of computer emulators written in JavaScript, including PCx86 for x86-based
  machines (8088 through 80386), C1Pjs for the 6502-based Ohio Scientific Challenger 1P, PC8080 for 8080-based
  machines like Space Invaders and the DEC VT100 Terminal, PDPjs with support for PDP-10 and PDP-11 machines, and
  emulators of classic programmable calculators, like the TI-57.  PCjs (formerly JSMachines) also provides an archive
  of selected historical PC software, publications, and reference materials.
baseurl: ""
url: "http://www.pcjs.org"
twitter_username: jeffpar
github_username:  jeffpar

left_brace: "{"
right_brace: "}"
encoding: UTF-8

# Build settings

exclude: ["index.html", "**/index.html", "bin", "logs", "node_modules", "src", "**/src", "tmp", "**/tmp", "videos", "web", "**/archive", "**/ecp", "**/c64", "**/private", "**/restricted", "**/unlisted", ".git", ".idea", "/Gemfile", "/Gemfile.lock", "/Gruntfile.js", "/gulpfile.js", "/notes.md", "/server.js", "/*.sh"]
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

# Custom site settings

pcjs:
  domain: pcjs.org    # whereas site.url is used for linking purposes, site.pcjs.domain is used for display purposes
  version: 1.40.0     # IMPORTANT: keep pcjs.version in sync with package.json:version
  compiled: true      # by default, the compiled pcjs.version scripts will be used (eg, pcx86.js, pc8080.js, etc)
